Created @scriptural/react package
eten-tech-foundation/scripture-editors pull request #221
Opened 2024-12-31 19:54 UTC by abelpz

Created lexical editor package for supporting usj

2025-01-16 00:19 UTC, irahopkinson reviewed
I'm publishing this partial review for now since GH is acting weird.

2025-01-16 01:43 UTC, irahopkinson reviewed
Next partial review (GH still acting weird - perhaps its is the large number of files)

2025-01-16 01:43 UTC, irahopkinson commented on packages/scriptural-react/CONTRIBUTING.md
> +   - Update CHANGELOG.md
The `CHANGELOG.md` file doesn't yet exist.

2025-01-16 01:43 UTC, irahopkinson commented on packages/scriptural-react/package.json
> +    "@lexical/react": "^0.21.0"
Maybe I'm wrong but aren't both of these lexical items actually `dependencies` rather than `peerDependencies`?

2025-01-16 01:43 UTC, irahopkinson commented on packages/scriptural-react/package.json
> +  },
Would you mind adding in volta to keep things consistent:
```json
  "volta": {
    "extends": "../../package.json"
  }
```

2025-01-16 01:43 UTC, irahopkinson commented on apps/scriptural/package.json
> +  }
Would you mind adding in volta to keep things consistent:
```json
  "volta": {
    "extends": "../../package.json"
  }
```

2025-01-16 04:19 UTC, irahopkinson reviewed
Another partial review. I've run out of week now. I'll get back to this when I get back after next week. Sorry for the delay.

2025-01-16 04:19 UTC, irahopkinson commented on packages/scriptural-react/src/plugins/ScripturalNodesMenuPlugin/useScripturalMarkersForMenu.ts
> +    return [...new Set([contextMarker, ...markerChildren, ...(markerAlike || [])])]
NIT use null coalescing operator instead, i.e. `markerAlike ?? []`.

2025-01-16 04:19 UTC, irahopkinson commented on packages/scriptural-react/vite.config.ts
I would appreciate a run through of this file with you.

2025-01-28 16:59 UTC, abelpz commented on apps/scriptural/src/App.tsx
> +            usj={editorState ? undefined : (getInitialUsj("TIT") ?? createEmptyUsj("TIT"))}
Yes it could be, it the cache was cleaned or entering for the first time. This is an example app of how the editor library could be used.

2025-01-28 17:00 UTC, abelpz commented on apps/scriptural/src/App.tsx
> +      return JSON.stringify(cached.data);
I might remove all of this cache expiring thing, this was just the AI agent trying to add more stuff to the example.

2025-01-28 17:07 UTC, abelpz commented on packages/scriptural-react/package.json
> +    "@lexical/react": "^0.21.0"
Not for this version of the package. Since I am allowing the user to add their own lexical extensions if needed, and they will probably need some lexical Types or functions that would not be bundled with this package. First it was a dependency but had to change it because of the above.

2025-01-28 17:14 UTC, abelpz commented on packages/scriptural-react/CONTRIBUTING.md
> +   git remote add upstream https://github.com/bible-technology/scripture-editors.git
whoops, AI did a great Job with documentation, so good that I trusted it wouldn't fail with this.

2025-01-28 17:16 UTC, abelpz commented on packages/scriptural-react/src/plugins/ChapterVerseUpdatePlugin/index.tsx
> +    editor.registerNodeTransform(TextNode, (node) => {
You are right, some times I forget to do it, mostly if I am on a deadline. Thanks for catching that.

2025-01-28 17:18 UTC, abelpz commented on packages/scriptural-react/src/plugins/ChapterVerseUpdatePlugin/index.tsx
> +    editor.registerNodeTransform(TextNode, (node) => {
Good idea, thanks for suggesting it, will do.

2025-01-28 17:21 UTC, abelpz commented on packages/scriptural-react/vite.config.ts
Sure, I can meet at the same time as usual, anyday you can.

2025-01-28 18:01 UTC, abelpz commented on packages/shared/converters/usj/core/usj.d.ts
Thanks!

2025-02-24 00:27 UTC, irahopkinson requested changes
Finally getting back to this review. It would be good to talk about your USJ nodes and if we can combine our usage of nodes.

2025-02-24 00:27 UTC, irahopkinson commented on packages/shared/nodes/usfm/UsfmElementNode.ts
> +export type SerializedScriptureElementNode = Spread<
Are you sure this should be renamed? It now clashes with another type of that same name. I would revert the 2 changes to this file if its not intentional.

2025-02-24 00:27 UTC, irahopkinson commented on packages/shared/utils/scriptureMarkers/getScripturalMarkerActions.ts
> +  let nodeType: UsjNode["type"] | undefined = undefined;
NIT: assigning to `undefined` isn't needed since declaring it makes it undefined.

2025-04-29 19:58 UTC, irahopkinson commented on packages/shared/converters/usj/core/usj.d.ts
> +  [key: `x-${string}`]: string;
I checked with the head of the USX/J/FM committee and it should be both `x-` and `z-` for properties. He helped me understand more about this if you want to chat in more detail.

2026-06-29 01:23 UTC, irahopkinson commented
Closing for now since no recent progress.

2026-06-29 01:23 UTC, closed without merging